### ISSUE TITLE
Entering through Fire Exit pushes me outside of the map

### ISSUE THREAD

**Issue by jerseymaster2003** [Toliann/HyperionStationInterior#1]
Hi,
Love the new interior.  Only issue i've had is entering through fire exit pushes me to the side of the door that's outside of the map. 
Thanks for all the great content

**Comment by jerseymaster2003** [comment]
tried .0.0.2.  this version makes my game crash most of the time

**Comment by Toliann** [comment]
i'll fix it when i have time
